[package]
name = "rocketsimulation_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
eframe = { version = "0.23.0", features = ["wgpu"] }
encase = { version = "0.6.1", features = ["cgmath"] }
enum-map = "2.6.3"
